### ISSUE TITLE
Include process/pane info in notification

### ISSUE THREAD

**Issue by ChanderG** [ChanderG/tmux-notify#1]
Include some kind of identification of the process / pane in the notification.

**Comment by rickstaa** [comment]
@ChanderG Thanks a lot for the amazing plugin! It really helps my workflow. I just send you a pull request in which I fixed one small bug and added some features that I myself found useful. Let me know what you think. Feel free to change my code and the tmux-option names in any way you desire.

**Comment by ChanderG** [comment]
@rickstaa , thanks. Glad to know that such small personal tools end up being useful for others too.

Thanks for taking time to create the PR. Feel free to open PRs for any other features you need too.

**Comment by rickstaa** [comment]
@ChanderG Great thanks a lot for being opensource! I send you another pull request with some small changes. I also opened to seperate topics for the features I want to implement later this year. Maybe you can add a `feature` and `fix` label to the issues pane. You can also add me as a collaborator if you want to.

**Comment by ChanderG** [comment]
@rickstaa , feel free to add the issue labels as needed.

**Comment by rickstaa** [comment]
@ChanderG Great I added them ass well as issue templates.
