### ISSUE TITLE
Add the ability to change focus automatically when process finishes

### ISSUE THREAD

**Issue by rickstaa** [ChanderG/tmux-notify#15]
I just noticed that @nat-chan created a very useful feature in his fork. This new feature automatically switches focus to the finished window. I think this would be good. I, however, think it should not be the default as it is currently in @nat-chan's branch.

### Proposal

My Idea is to pull the changes of @nat-chan into my fork and modify them slightly such that user has two ways to monitor a pane:

- `prefix + m`: The regular pane monitor option.
- `prefix + alt + m`: Now the pane is monitored, and the focus is returned to the pane when it finishes.

Alternatively, we can of course also use a tmux-option to change this behaviour, but I think the above method would allow users to decide on a pane basis whether the want to return the focus. @ChanderG and @bruno- what do you think about this new feature?

**Comment by ChanderG** [comment]
Sounds good - per pane selection like you mention seems better.

**Comment by rickstaa** [comment]
@ChanderG great I will start working on it after we resolved #7.

**Comment by rickstaa** [comment]
This feature is added in #17
