### ISSUE TITLE
Move the tmux-notify plugin to the tmux-plugins orginaization

### ISSUE THREAD

**Issue by rickstaa** [ChanderG/tmux-notify#16]
@ChanderG @bruno- Maybe it's an idea after we merged #10 #15 that we transfer the plugin to the[tmux-plugins orginaization](https://github.com/orgs/tmux-plugins)? This way this in my opinion very useful plugin reached more people and resides at a more central place inside the community. In addition, we can also create pull requests for the plugin to be added to the list found in [rothgar/awesome-tmux](https://github.com/rothgar/awesome-tmux).

**Comment by ChanderG** [comment]
I would not mind transferring ownership to the `tmux-plugins` org if @bruno- is interested. 

@rickstaa I think we can definitely open a PR to add to the awesome-tmux list.

**Comment by rickstaa** [comment]
> I would not mind transferring ownership to the `tmux-plugins` org if @bruno- is interested. 
> 
> @rickstaa I think we can definitely open a PR to add to the awesome-tmux list.

Great let's wait on @bruno- 's response then. I will create the pull request to the awesome-tmux after I complete #15.

**Comment by rickstaa** [comment]
I added our plugin to [rothgar/awesome-tmux/pulls](https://github.com/rothgar/awesome-tmux/pulls). I will close this issue as we did not hear back from @bruno-. I think the plugin userbase might be too small to include it to the [tmux-plugins organization](https://github.com/tmux-plugins).
