### ISSUE TITLE
Pressing `prefix + M` to cancel the monitor doesn't work

### ISSUE THREAD

**Issue by ntwk** [ChanderG/tmux-notify#20]
Upon pressing `prefix + M`, tmux displays the message `Pane not monitored...` even if the pane is actively being monitored.

**Steps to reproduce**

1. Press `prefix + m` to start monitoring a pane with an active task.
2. Press `prefix + M` to cancel the monitoring.

**Expected behavior**

Tmux should should display the message `Pane monitoring canceled...`.

**Actual behavior**

Tmux displays the message `Pane not monitored...`.

**My environment is as follows**

- Platform: Linux 5.11.2
- Tmux version: 3.1c
- TERM inside tmux: tmux-256color
- TERM outside tmux: rxvt-unicode-256color

**Comment by ntwk** [comment]
The issue appears to be that the following check is failing:

https://github.com/ChanderG/tmux-notify/blob/52b086bce19d659632e393e1aa478c0d04413289/scripts/cancel.sh#L20

Looking at `cancel.sh` and `notify.sh` reveals that these two scripts are constructing `PID_FILE_PATH` differently.  The `cancel.sh` script is constructing the wrong PID filename and it fails to find the proper PID file that was previously created by `notify.sh`.

Currently, `cancel.sh` constructs `PID_FILE_PATH` like so:

https://github.com/ChanderG/tmux-notify/blob/52b086bce19d659632e393e1aa478c0d04413289/scripts/cancel.sh#L12-L17

Whereas `notify.sh` uses the following code.  Note in particular that `notify.sh` is using different command substitutions for `PANE_NR` and `PANE ID`:

https://github.com/ChanderG/tmux-notify/blob/52b086bce19d659632e393e1aa478c0d04413289/scripts/notify.sh#L35-L40

A possible solution would be to ensure that both scripts are using the same code to construct the PID filename.  The above environment variables could be reconciled and declared in `.tmux-notify/scripts/variables.sh` as both `notify.sh` and `cancel.sh` source this file.  This would solve the problem and eliminate the duplicated code.

I am currently working on a fix for #19 which should also resolve this issue.

**Comment by rickstaa** [comment]
@ntwk Good catch I think this error was introduced in one of my latest commits. Sorry for that. I will take a look at the pull request you created.
