### ISSUE TITLE
Add tags to the repo

### ISSUE THREAD

**Issue by cynicaljoy** [ChanderG/tmux-notify#28]
Feature/suggestion: tag the repo with `tmux` and `tmux-plugins` so it can be more easily found

**Comment by rickstaa** [comment]
@cynicaljoy Good suggestion! I, however, do not have enough rights to do this. @ChanderG can you take a look at this?

**Comment by rickstaa** [comment]
@cynicaljoy In the meantime, while we wait on @ChanderG to add the tas I added this plugin to the https://github.com/tmux-plugins/list so that more people can find it 🙂.

**Comment by rickstaa** [comment]
@ChanderG, just a friendly reminder to add the `tmux` and `tmux-plugins` tags to the repository. Feel free to [transfer the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to me if you don't have time to maintain it anymore.

**Comment by rickstaa** [comment]
@ChanderG trying thus again. Can you please add the labels suggested above. It is a 20 second task but I sadly don't have the right permissions. 😅

**Comment by rickstaa** [comment]
@ChanderG I would appreciate it if you could add these tags so that we can close this simple issue 👍🏻.

**Comment by rickstaa** [comment]
@ChanderG I just fixed all the open issues and feature requests. I also improved the code 👍🏻.

**Comment by rickstaa** [comment]
@ChanderG In v1.4.0 of Tmux-notify, I've added a new feature to help that allows users to receive Telegram notifications when a shell processes finishes.

**Comment by rickstaa** [comment]
@ChanderG did you see my emails? Since I love this tool, I'm happy to maintain this repository if you don't have time to maintain it any more (see https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by cynicaljoy** [comment]
@rickstaa it might be time to fork the repo 😢

**Comment by rickstaa** [comment]
> @rickstaa it might be time to fork the repo cry

I will give @ChanderG a week longer to respond, after that, I will add a deprecation message, and we can work from my fork https://github.com/rickstaa/tmux-notify. I already added the tags/topics you requested there so that more people can find this tool 🚀.

**Comment by rickstaa** [comment]
> > @rickstaa it might be time to fork the repo cry
> 
> I will give @ChanderG a week longer to respond, after that, I will add a deprecation message, and we can work from my fork https://github.com/rickstaa/tmux-notify. I already added the tags/topics you requested there so that more people can find this tool rocket.

I, however, would really like to continue on the original since I don't know if a detached fork will show the same contributors in the sidebar 🤔.

**Comment by rickstaa** [comment]
I asked the GitHub support tool to detach my fork, let's see what history and info it retains 👍🏻.

**Comment by cynicaljoy** [comment]
oh I agree, I typically despise forks as people are too quick to fork rather than try to work with maintainers. but in the case where a maintainer has ghosted the repo and people are using it I think it's the only way. GitHub Support historically doesn't intervene when I wish they would.

**Comment by rickstaa** [comment]
> oh I agree, I typically despise forks as people are too quick to fork rather than try to work with maintainers. but in the case where a maintainer has ghosted the repo and people are using it I think it's the only way. GitHub Support historically doesn't intervene when I wish they would.

Same here, de-forking is my last resort 😅. However, the last response I received from the author was more than 3 years ago (see https://github.com/ChanderG/tmux-notify/issues/16#issuecomment-703053967) and I tried to contact him on all channels. 

The de-forking just finished, and it looks like all the history was retained 🎉. The only contributor that is not shown any more is @bruno- because I think those initial commits were cherry-picks. Anyway, we are good to continue the maintained on my new orphan repository 👍🏻. Alternatively, as stated in https://github.com/ChanderG/tmux-notify/issues/16 I'm also okay with transferring the repository to the https://github.com/tmux-plugins organization and maintaining it from there if @bruno-, @ctjhoa and @jbnicolai are interested.

**Comment by rickstaa** [comment]
I will also update https://github.com/rothgar/awesome-tmux after that so that people can find the maintained version.

**Comment by rickstaa** [comment]
@cynicaljoy I added the `tmux`, `tmux-plugin` and `tmux-plugins` tags to the repository. If you have any other suggestions feel free to let me know.
