### ISSUE TITLE
Add ability to change key maps

### ISSUE THREAD

**Issue by uzza1hossain** [ChanderG/tmux-notify#29]
I want to change the keymap to prefix - n. Because prefix-m for activating mouse. How can I do that?

**Comment by rickstaa** [comment]
@uzza1hossain Thanks for your question. We currently do not have an easy way to change the key binding. Feel free to open a pull request. The best way to change the keybinding at the current time is to overwrite it in your `.tmux.conf`. The keyboard shortcuts of the `tmux-notify` plugin are set in the following code:

https://github.com/ChanderG/tmux-notify/blob/50a9b49e3760a2d1c595ed3425f680186feeb47f/tnotify.tmux#L16-L22

You can use this syntax in your `.tmux.conf` file to unbind the keyboard bindings that are set by the `tmux-notify` plugin and reset them and remap them. Hope that helps!

**Comment by rickstaa** [comment]
Might you want to contribute to this repository you can see an example of how to make the keybindings customizable in https://github.com/tmux-plugins/tmux-fpp/blob/master/fpp.tmux and https://github.com/tmux-plugins/tmux-urlview/blob/master/urlview.tmux.

**Comment by rickstaa** [comment]
Closing this since I did not receive a response and the overwrite method is, in my opinion , sufficient.
