### ISSUE TITLE
Execute custom commands when processes are complete

### ISSUE THREAD

**Issue by seekstar** [ChanderG/tmux-notify#36]
I am using `tmux` on a server, and I want to make the `tmux` on a server send a notification to my desktop when processes are complete. It seems that `tmux-notify` currently only send notifications via `notify-send`. However, it seems that `notify-send` can not send notifications to remote desktop (i.e., my personal desktop).

I think allowing executing custom commands when processes are complete is helpful in this case. I can write a script that sends an email to my mailbox or a script that logs in to my personal desktop and execute `zenity` or something else to prompt a notification on my personal desktop.

**Comment by rickstaa** [comment]
Related to #30.

**Comment by rickstaa** [comment]
Maybe this helps https://github.com/mikaelbr/node-notifier/issues/200.

**Comment by rickstaa** [comment]
I created https://github.com/rickstaa/tmux-notify/pull/5 to add your feature request. Please let me know what you think and if there are ways to improve this feature (i.e. make it more safe).

**Comment by rickstaa** [comment]
Let's track this in https://github.com/rickstaa/tmux-notify/issues/6.
